server.port=8085
spring.application.name=api-gateway

# Configuración de rutas amigable con el analizador de VS Code
spring.cloud.gateway.server.webmvc.routes[0].id=clientes-route
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://ms-clientes
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/clientes/**

spring.cloud.gateway.server.webmvc.routes[1].id=productos-route
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://ms-productos
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/productos/**

spring.cloud.gateway.server.webmvc.routes[2].id=ventas-route
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://ms-ventas
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/ventas/**

spring.cloud.gateway.server.webmvc.routes[3].id=users-route
spring.cloud.gateway.server.webmvc.routes[3].uri=lb://ms-usuarios
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/users/**

jwt.secret=7v!X$9mQ#zK4wP@b2eR&uG*1yT5sC(8jM0xF%3dA6nL_pQ)9vK-eW+sY_xZ#7wM!pQ

# Configuración para conectarse al Servidor Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

#Gemini hizo esto para no tener tantos mensajes.
# 1. Quitar el banner de Spring (el dibujo de inicio)
spring.main.banner-mode=off

# 2. Definir un formato limpio y con colores
# %clr() añade colores: Verde para INFO, Rojo para ERROR, Amarillo para WARN
# Fuerza el uso de colores ANSI en la consola
spring.output.ansi.enabled=ALWAYS

# Formato ultra-limpio con colores (pégalo tal cual)
logging.pattern.console=%clr(%d{HH:mm:ss}){faint} %clr(%-5p) %clr(:){faint} %clr(%m){cyan}%n

# 3. Silenciar lo que no es tu código
logging.level.root=WARN
logging.level.com.apimicroservice.demo=INFO
