server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: clientes-route
          uri: lb://ms-cliente
          predicates:
            - Path=/api/clientes/**

        - id: productos-route
          uri: lb://ms-productos
          predicates:
            - Path=/api/productos/**

        - id: ventas-route
          uri: lb://ms-ventas
          predicates:
            - Path=/api/ventas/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/