spring.application.name=eureka-server
server.port=8761

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

#Gemini hizo esto para no tener tantos mensajes.
# 1. Quitar el banner de Spring (el dibujo de inicio)
spring.main.banner-mode=off

# 2. Definir un formato limpio y con colores
# %clr() añade colores: Verde para INFO, Rojo para ERROR, Amarillo para WARN
# Fuerza el uso de colores ANSI en la consola
spring.output.ansi.enabled=ALWAYS

# Formato ultra-limpio con colores (pégalo tal cual)
logging.pattern.console=%clr(%d{HH:mm:ss}){faint} %clr(%-5p) %clr(:){faint} %clr(%m){cyan}%n

# 3. Silenciar lo que no es tu código
logging.level.root=WARN
logging.level.com.apimicroservice.demo=INFO
