spring.application.name=web
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

spring.main.banner-mode=off
spring.output.ansi.enabled=ALWAYS
logging.pattern.console=%clr(%d{HH:mm:ss}){faint} %clr(%-5p) %clr(:){faint} %clr(%m){cyan}%n
logging.level.root=WARN
logging.level.com.apimicroservice.users=INFO


server.servlet.session.tracking-modes=cookie