spring.application.name=clientes-api
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=db_clientes;encrypt=false;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=12345678
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

#Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Gemini hizo esto para no tener tantos mensajes.
# 1. Quitar el banner de Spring (el dibujo de inicio)
spring.main.banner-mode=off

# 2. Definir un formato limpio y con colores
# %clr() añade colores: Verde para INFO, Rojo para ERROR, Amarillo para WARN
# Fuerza el uso de colores ANSI en la consola
spring.output.ansi.enabled=ALWAYS

# Formato ultra-limpio con colores (pégalo tal cual)
logging.pattern.console=%clr(%d{HH:mm:ss}){faint} %clr(%-5p) %clr(:){faint} %clr(%m){cyan}%n

# 3. Silenciar lo que no es tu código
logging.level.root=WARN
logging.level.com.apimicroservice.demo=INFO

# 4. Evitar el aviso amarillo de JPA
spring.jpa.open-in-view=false